# Conectarnos a la base de datos 
import oracledb
# Rescatar variables de entorno
import os
# Implementar hasheo de contraseñas
import bcrypt
# Implementar peticiones HTTP
import requests
from dotenv import load_dotenv
# Importar tipo de dato Optional    
from typing import Optional
# Importar libreria de fechas
import datetime

# Obtener la ruta donde está guardado este archivo main.py
directorio_actual = os.path.dirname(os.path.abspath(__file__))
# Construir la ruta al archivo .env
ruta_env = os.path.join(directorio_actual, '.env')
# Cargar el archivo .env especificando la ruta
load_dotenv(ruta_env)

# Rescatar las credenciales de conexion con Oracle
username = os.getenv("ORACLE_USER")
dsn = os.getenv("ORACLE_DSN")
password = os.getenv("ORACLE_PASSWORD")

class Database:
    def __init__(self,username, password, dsn):
        self.username = username
        self.password = password
        self.dsn = dsn

    def get_connection(self):
        return oracledb.connect(user=self.username, password=self.password, dsn=self.dsn)
    
    def create_all_tables(self):
        # 1. Tabla de Usuarios (Con ID autoincrementable para evitar errores)
        sql_users = """
            CREATE TABLE USERS(
                id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                username VARCHAR2(50) UNIQUE,
                password VARCHAR2(100)
            )
        """
        # 2. Tabla de Historial (Requisito de la Rubrica)
        sql_history = """
            CREATE TABLE HISTORIAL(
                id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                indicador VARCHAR2(20),
                valor NUMBER,
                fecha_indicador VARCHAR2(20),
                fecha_consulta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                usuario_consulta VARCHAR2(50),
                fuente VARCHAR2(50)
            )
        """
        # Intentamos crear las tablas. Si existen, ignoramos el error.
        for query in [sql_users, sql_history]:
            try:
                self.query(query)
                print("Tabla creada correctamente.")
            except:
                pass

    def query(self, sentence: str, parameters: Optional[dict] = None):
        # print(f"Ejecutando query: {sentence}") # Descomenta si quieres ver el SQL
        try:
            with self.get_connection() as connection:
                with connection.cursor() as cursor:
                    resultado = cursor.execute(sentence, parameters or {})
                    if sentence.strip().upper().startswith("SELECT"):
                        return resultado.fetchall()
                    connection.commit()
                    return True
        except oracledb.DatabaseError as error:
            print(f"Error en la base de datos: {error}")
            return []

# Generar autenticacion
class Auth:
    @staticmethod
    def register(db: Database, username: str, password: str):
        # Validación simple (Rubrica: Validar ingreso)
        if not username or not password:
            print("Usuario y contraseña no pueden estar vacíos")
            return

        salt = bcrypt.gensalt(12)
        hashed_password = bcrypt.hashpw(password.encode('utf-8'), salt)
        
        # Eliminamos el 'id' manual para dejar que la base de datos lo genere sola
        usuario = {
            "username": username,
            "password": hashed_password.decode('utf-8') # Guardar como string
        }

        db.query(
            "INSERT INTO USERS (username, password) VALUES (:username, :password)",
            usuario
        )
        print("Usuario registrado con éxito.")

    @staticmethod
    def login(db: Database, username: str, password: str) -> bool:
        resultado = db.query(
            "SELECT * FROM USERS WHERE username = :username",
            {"username" : username}
        ) 
        
        if not resultado:
            return False

        # En la BD: id es [0], username [1], password [2]
        usuario_data = resultado[0] 
        password_hashed_bd = usuario_data[2]
        
        # Comparamos
        return bcrypt.checkpw(password.encode('utf-8'), password_hashed_bd.encode('utf-8'))

"""
Unidad de Fomento (UF)
Indice de Valor Promedio (IVP)
Indice de Precios al Consumidor (IPC)
Unidad Tributaria Mensual (UTM)
Dólar -> CLP
EURO -> CLP
"""

class Finance:
    def __init__(self, db: Database, base_url: str = "https://mindicador.cl/api"):
        self.base_url = base_url
        self.db = db

    def get_indicator(self, indicator: str, fecha: str = None, usuario: str = "anonimo"):
        if not indicator:
            return print("Indicador faltante")
        
        # Si no hay fecha, usaremos la de hoy
        if not fecha:
            now = datetime.datetime.now()
            fecha = f"{now.day}-{now.month}-{now.year}"
            
        try:
            url = f"{self.base_url}/{indicator}/{fecha}"
            response = requests.get(url=url)
            
            if response.status_code != 200:
                print("No hay datos para esa fecha o indicador.")
                return

            data = response.json()
            
            if not data['serie']:
                print("API respondió pero sin valores para esa fecha.")
                return

            valor = data['serie'][0]['valor']
            print(f"--> El valor de {indicator} el {fecha} es: {valor}")

            # --- AQUÍ GUARDAMOS EN LA BD (Requisito Rúbrica) ---
            self.save_history(indicator, valor, fecha, usuario)

        except Exception as e:
            print(f"Error al obtener indicador: {e}")

    def save_history(self, indicador, valor, fecha_ind, usuario):
        # Almacenar en base de datos: nombre, fecha valor, fecha consulta, usuario, sitio
        sql = """
            INSERT INTO HISTORIAL (indicador, valor, fecha_indicador, usuario_consulta, fuente)
            VALUES (:ind, :val, :fec, :usr, :fte)
        """
        params = {
            "ind": indicador,
            "val": valor,
            "fec": fecha_ind,
            "usr": usuario,
            "fte": self.base_url
        }
        self.db.query(sql, params)
        print("(Consulta guardada en historial)")

    def consultar_todo(self, usuario):
        print("\n--- Consultando Indicadores de Hoy ---")
        self.get_indicator("uf", usuario=usuario)
        self.get_indicator("dolar", usuario=usuario)
        self.get_indicator("euro", usuario=usuario)
        self.get_indicator("utm", usuario=usuario)
        self.get_indicator("ivp", usuario=usuario)



if __name__ == "__main__":
    
    # 1. Validar variables de entorno (Para evitar error DPY-4001)
    if not username or not password:
        print("ERROR: No se cargaron las credenciales del archivo .env")
        exit()

    # 2. Iniciar objeto Base de Datos
    mi_db = Database(username, password, dsn)
    
    # 3. Crear tablas (Solo se crean si no existen)
    mi_db.create_all_tables()

    # 4. Iniciar objeto de Finanzas
    sistema_finanzas = Finance(db=mi_db)

    print("\nBienvenido al Sistema de Gestión de Indicadores")
    usuario_actual = None

    while True:
        if not usuario_actual:
            print("\n1. Iniciar Sesión")
            print("2. Registrarse")
            print("3. Salir")
            opcion = input("Seleccione: ")

            if opcion == "1":
                u = input("Usuario: ")
                p = input("Contraseña: ")
                if Auth.login(mi_db, u, p):
                    usuario_actual = u
                    print("¡Bienvenido!")
                else:
                    print("Credenciales incorrectas.")
            
            elif opcion == "2":
                u = input("Nuevo Usuario: ")
                p = input("Nueva Contraseña: ")
                Auth.register(mi_db, u, p)
            
            elif opcion == "3":
                print("Saliendo del programa...")
                break
        else:
            print(f"\n--- Menú Usuario: {usuario_actual} ---")
            print("1. Consultar UF")
            print("2. Consultar Dólar")
            print("3. Consultar Euro")
            print("4. Consultar IVP")
            print("5. Consultar IPC (Ingresar fecha)")
            print("6. Cerrar Sesión")
            opc = input("Seleccione indicador: ")

            if opc == "1":
                sistema_finanzas.get_indicator("uf", usuario=usuario_actual)
            elif opc == "2":
                sistema_finanzas.get_indicator("dolar", usuario=usuario_actual)
            elif opc == "3":
                sistema_finanzas.get_indicator("euro", usuario=usuario_actual)
            elif opc == "4":
                sistema_finanzas.get_indicator("ivp", usuario=usuario_actual)
            elif opc == "5":
                f = input("Ingrese fecha (dd-mm-yyyy): ")
                sistema_finanzas.get_indicator("ipc", fecha=f, usuario=usuario_actual)
            elif opc == "6":
                usuario_actual = None
                print("Sesión cerrada.")
            else:
                print("Opción no válida")